#!/usr/bin/env php
<?php

// Define the application route.
define('ROOTDIR', rtrim(dirname(__FILE__), '/') . '/');

// Load the application bootstrap.
require_once 'bootstrap/bootstrap.php';

// Initialize console.
Spire\Console\Console::initialize();
